### PR TITLE
Add mqtt-stream docs

### PR DESCRIPTION
**Pull request by RanMaoyi**

### CODE REVIEW

**Review by lee-emqx — APPROVED** [review]

**Review by JaylinYu — APPROVED** [review]
Cool, but it doesnt get updated if you don't modify directory

**Comment by OdyWayne** [comment]
you can use the script `prview.sh` in the `docs` directory to preview the docs.  You can preview in `http://localhost:8080/docs/en/latest/` and `http://localhost:8080/docs/zh/latest/`

**Comment by RanMaoyi** [comment]
> Cool, but it doesnt get updated if you don't modify directory

done

**Review by JaylinYu — COMMENTED** [review]
thats it

**Review by wanghaEMQ — COMMENTED** [review]
Cool

**Pull request merged**
