### PR TITLE
* FIX [broker] Update the confusing interface proto_work_init.

### PR DESCRIPTION
**Pull request by wanghaEMQ**

### CODE REVIEW

**Review by xinyi-xs — APPROVED** [review]

**Comment by JaylinYu** [comment]
better check with CI

**Review by xinyi-xs — APPROVED** [review]

**Comment by JaylinYu** [comment]
@OdyWayne REST_API tests still fail

**Comment by wanghaEMQ** [comment]
Yes. It's weird

**Comment by OdyWayne** [comment]
> @OdyWayne REST_API tests still fail

This is not the issue of rest-api alone. FTs are not independent of each other. FTs need some rework.

**Comment by JaylinYu** [comment]
> > @OdyWayne REST_API tests still fail
> 
> 
> 
> This is not the issue of rest-api alone. FTs are not independent of each other. FTs need some rework.

Cool, exclude the http test for now

**Pull request merged**
