### PR TITLE
Set bridge backoff from configuration file

### PR DESCRIPTION
**Pull request by wanghaEMQ**

### CODE REVIEW

**Comment by wanghaEMQ** [comment]
@OdyWayne Should we add document for this option? And where?

**Review by RanMaoyi — APPROVED** [review]

**Review by OdyWayne — APPROVED** [review]

**Comment by JaylinYu** [comment]
will merge nanonng first

**Comment by wanghaEMQ** [comment]
Yap it has been done in nanonng.

**Review by lee-emqx — APPROVED** [review]

**Review by JaylinYu — APPROVED** [review]
remember to move nng head

**Pull request merged**
